# Generated by Django 4.2.3 on 2024-04-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_referal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valid_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('token', models.CharField(blank=True, max_length=400, null=True)),
                ('userid', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
